### ISSUE TITLE
RuntimeError: Unable to open file 'model.bin' in model 'facebook/nllb-200-distilled-600M'

### ISSUE THREAD

**Issue by Prasanta-Hembram** [janvarev/OneRingTranslator#2]
Hello, I have tried installing it using the following steps [here ](https://github.com/janvarev/OneRingTranslator-installer
). Also, when I click on **start-webapi.bat** it woks well I'm able to translate using this api request: http://127.0.0.1:4990/translate?text=Hi%21&from_lang=en&to_lang=fr getting result "Salut!" . I want to use fb_nllb_ctranslate2 plugin for translation, but each time I make request I get **RuntimeError: Unable to open file 'model.bin' in model 'facebook/nllb-200-distilled-600M'** . I don't know where facebook/nllb-200-distilled-600M should be created, I already have model.bin file?? 

```
Error init translation plugin fb_nllb_ctranslate2...
Traceback (most recent call last):
  File "D:\NewNLLB\OneRingTranslator\oneringcore.py", line 80, in init_translator_engine
    self.translators[translator_engine][0](self)
  File "D:\NewNLLB\OneRingTranslator\plugins\plugin_fb_nllb_ctranslate2.py", line 269, in init
    model = ctranslate2.Translator(core.plugin_options(modname).get("model"), device=to_device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unable to open file 'model.bin' in model 'facebook/nllb-200-distilled-600M'
INFO:     127.0.0.1:50298 - "GET /translate?text=Hello&from_lang=eng_Latn&to_lang=sat_Olck&translator_plugin=fb_nllb_ctranslate2 HTTP/1.1" 200 OK
```

**Comment by janvarev** [comment]
Hi!

For facebook/nllb-200-distilled-600M please use fb_nllb_translate version. This version is simpler, and will download net automatically.

fb_nllb_ctranslate2 requires manual downloads some special versions prepared with CTranslate2 conversion. Example  in JustFrederick huggingface account.

**Comment by janvarev** [comment]
https://huggingface.co/JustFrederik account with CTranslate2 prepared models. You need download them manually, and place in folder in OneRingTranslator folder, and then make a link.

**Comment by Prasanta-Hembram** [comment]
Thank you @janvarev It worked!!🤩🤩
